
title: "hi! i'm abby mcclain"
author: "abby mcclain"
description: "made with <b style=\"color: #f45;\">☕</b> and <b style=\"color: #ffcc00;\">🎧</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  ##- {file: "about_me.md", title: "about me"} ##
  - {file: "public_promo.md", title: "as seen in"}
  - {file: "from_the_field.md", title: "from the field"}
  - {file: "publications.md", title: "publications"}
  - {file: "creative_works.md", title: "design"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/armcclain"}
  - {title: Instagram, icon: camera, url: "https://www.instagram.com/the_primate_diaries/?igsh=dHhtM2F2ZXMxdWNv&utm_source=qr#"}
  - {title: Spotify, icon: spotify, url: "https://open.spotify.com/user/abimccla?si=f2e2eaa623f5494d&nd=1&dlsi=2e987cd6a31a42b7"}
  

 

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-gist
